---
- name: Configure Servers
  hosts: all
  become: yes
  tasks:
    - name: Include package configuration tasks
      include_role:
        name: all
      tags:
        - package
    - name: Include network configuration tasks
      include_role:
        name: all
      tags:
        - ip
        - dhcp4
        - dhcp6v1
        - resnet
        - dhcp6v2
        - route
        - vpn
        - dns
        - work-r0
        - work-r1
    - name: Include services configuration tasks
      include_role:
        name: all
      tags:
        - ntp
        - nfs
        - cups
    - name: Include security configuration tasks
      include_role:
        name: all
      tags:
        - firewalld
        - iptables
        - netsec