include:
  - local: 'gitlab-ci/ci-templates.yml'

stages:
  - configure_network
  - notify_network

# Шаблон для установки IP
.configure_ip:
  extends: .ip_template
  artifacts:
    paths:
      - $NOTIFY_FILES
    expire_in: 1 hour

# Шаблон для конфигурирования DHCPv4
.configure_dhcp4:
  extends: .dhcp4_template
  artifacts:
    paths:
      - $NOTIFY_FILES
    expire_in: 1 hour

# Шаблон для конфигурирования DHCPv6 (1 часть)
.configure_dhcp6v1:
  extends: .dhcp6v1_template
  artifacts:
    paths:
      - $NOTIFY_FILES
    expire_in: 1 hour

# Шаблон для активации сетевых интерфейсов ens36
.configure_resnet:
  extends: .resnet_template
  artifacts:
    paths:
      - $NOTIFY_FILES
    expire_in: 1 hour

# Шаблон для конфигурирования DHCPv6 (2 часть)
.configure_dhcp6v2:
  extends: .dhcp6v2_template
  artifacts:
    paths:
      - $NOTIFY_FILES
    expire_in: 1 hour

# Шаблон для настройки ROUTE на Client PC
.configure_route:
  extends: .route_template
  artifacts:
    paths:
      - $NOTIFY_FILES
    expire_in: 1 hour

# Шаблон для настройки VPN и OSPF
.configure_vpn:
  extends: .vpn_template
  artifacts:
    paths:
      - $NOTIFY_FILES
    expire_in: 1 hour

# Шаблон для настройки DNS
.configure_dns:
  extends: .dns_template
  artifacts:
    paths:
      - $NOTIFY_FILES
    expire_in: 1 hour

# Шаблон для настройки DNS
.configure_work0:
  extends: .work0_template
  artifacts:
    paths:
      - $NOTIFY_FILES
    expire_in: 1 hour

# Шаблон для настройки DNS
.configure_work1:
  extends: .work1_template
  artifacts:
    paths:
      - $NOTIFY_FILES
    expire_in: 1 hour

configured_ip:
  extends: .configure_ip
  variables:
    SERVER_LIMIT: 'r0_server'
    NOTIFY_FILES: 'r0_server_ip.txt'
  tags:
    - r0.server
  needs:
    - Installing_packages
  stage: configure_network

configured_dhcp4:
  extends: .configure_dhcp4
  variables:
    SERVER_LIMIT: 'r0_server'
    NOTIFY_FILES: 'r0_server_ip.txt'
  tags:
    - r0.server
  needs:
    - configured_ip
  stage: configure_network

configured_dhcp6v1:
  extends: .configure_dhcp6v1
  variables:
    SERVER_LIMIT: 'r0_server'
    NOTIFY_FILES: 'r0_server_ip.txt'
  tags:
    - r0.server
  needs:
    - configured_dhcp4
  stage: configure_network

configured_resnet:
  extends: .configure_resnet
  variables:
    SERVER_LIMIT: 'r0_server'
    NOTIFY_FILES: 'r0_server_ip.txt'
  tags:
    - r0.server
  needs:
    - configured_dhcp6v1
  stage: configure_network

configured_dhcp6v2:
  extends: .configure_dhcp6v2
  variables:
    SERVER_LIMIT: 'r0_server'
    NOTIFY_FILES: 'r0_server_ip.txt'
  tags:
    - r0.server
  needs:
    - configured_resnet
  stage: configure_network

configured_route:
  extends: .configure_route
  variables:
    SERVER_LIMIT: 'r0_server'
    NOTIFY_FILES: 'r0_server_ip.txt'
  tags:
    - r0.server
  needs:
    - configured_dhcp6v2
  stage: configure_network

configured_vpn:
  extends: .configure_vpn
  variables:
    SERVER_LIMIT: 'r0_server'
    NOTIFY_FILES: 'r0_server_ip.txt'
  tags:
    - r0.server
  needs:
    - configured_route
  stage: configure_network

configured_dns:
  extends: .configure_dns
  variables:
    SERVER_LIMIT: 'r0_server'
    NOTIFY_FILES: 'r0_server_ip.txt'
  tags:
    - r0.server
  needs:
    - configured_vpn
  stage: configure_network

configured_work0:
  extends: .configure_work0
  variables:
    SERVER_LIMIT: 'r0_server'
    NOTIFY_FILES: 'r0_server_ip.txt'
  tags:
    - r0.server
  needs:
    - configured_dns
  stage: configure_network

configured_work1:
  extends: .configure_work1
  variables:
    SERVER_LIMIT: 'r0_server'
    NOTIFY_FILES: 'r0_server_ip.txt'
  tags:
    - r0.server
  needs:
    - configured_work0
  stage: configure_network

# Уведомление после конфигурирования сети
notify_network:
  extends: .notify_template
  variables:
    PLAYBOOK_INDEX: "1"
    NOTIFY_FILES: 'r0_server_ip.txt'
    MESSAGE: "Результаты выполнения Ansible playbooks:\n1) playbook #2 выполнен успешно! \nНастроено: \n - IPv4 \n - IPv6 \n - DHCPv4 \n - DHCPv6 \n - Routing \n - VPN \n - OSPF \n - DNS\n"
  needs:
    - configured_work1
  stage: notify_network
